name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Generate sitemap.xml
        run: python generate_sitemap.py
      
      - name: Check if sitemap.xml changed
        id: check_changes
        run: |
          if git diff --quiet sitemap.xml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push sitemap.xml
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml"
          git push
